-- This table saves all the data related to a prn consumption - payment registration number.

CREATE TABLE pgateway.prn_consumed(
	prn character varying(13) NOT NULL,
	prn_data character varying(2000) NOT NULL,
	is_prn_valid boolean NOT NULL,
	cr_by character varying(256) NOT NULL,
	cr_dtimes timestamp NOT NULL,
	upd_by character varying(256),
	upd_dtimes timestamp,
	CONSTRAINT pk_prn_consumed_id PRIMARY KEY (prn)
);

COMMENT ON TABLE pgateway.prn_consumed IS 'PRN Consumed: Stores details of a PRN consumption.';
COMMENT ON COLUMN pgateway.prn_consumed.prn IS 'Payment Registration Number: Unique Id generated by URA API for payment of a tax head.';
COMMENT ON COLUMN pgateway.prn_consumed.prn_data IS 'PRN Data: Details of a PRN, stored in json format.';
COMMENT ON COLUMN pgateway.prn_consumed.is_prn_valid IS 'Is PRN Valid: Flag to mark whether the prn is valid or not valid';
COMMENT ON COLUMN pgateway.prn_consumed.cr_by IS 'Created By : ID or name of the user who create / insert record.';
COMMENT ON COLUMN pgateway.prn_consumed.cr_dtimes IS 'Created DateTimestamp : Date and Timestamp when the record is created/inserted';
COMMENT ON COLUMN pgateway.prn_consumed.upd_by IS 'Updated By : ID or name of the user who update the record with new values';
COMMENT ON COLUMN pgateway.prn_consumed.upd_dtimes IS 'Updated DateTimestamp : Date and Timestamp when any of the fields in the record is updated with new values.';
