-- This table saves all the data related to a prn consumption transaction related to a regId.

CREATE TABLE pgateway.prn_transaction(
	id character varying(36) NOT NULL,
	prn character varying(13) NOT NULL,
	reg_id character varying(39) NOT NULL,
	cr_by character varying(256) NOT NULL,
	cr_dtimes timestamp NOT NULL,
	CONSTRAINT pk_prn_transaction_id PRIMARY KEY (id, prn)
);

COMMENT ON TABLE pgateway.prn_transaction IS 'PRN Transaction: Stores details of a PRN transaction based on consumption.';
COMMENT ON COLUMN pgateway.prn_consumed.id IS 'Unique identifier for the record, stored as a UUID string.';
COMMENT ON COLUMN pgateway.prn_transaction.prn IS 'Payment Registration Number: Unique Id generated by URA API for payment of a tax head.';
COMMENT ON COLUMN pgateway.prn_transaction.reg_id IS 'Registration Id: Application Id for the individual tagged to a PRN.';
COMMENT ON COLUMN pgateway.prn_consumed.cr_by IS 'Created By : ID or name of the user who create / insert record.';
COMMENT ON COLUMN pgateway.prn_consumed.cr_dtimes IS 'Created DateTimestamp : Date and Timestamp when the record is created/inserted';
